#!/bin/sh

# A script that converts audio files into formats compatible with media players like the SanDisk Sansa.

goal_ext=".mp3"
tail="_$(echo $goal_ext | tr '[:lower:]' '[:upper:]' | sed 's/\.//g')"
folder="$(basename "$PWD")${tail}"
pfl="/tmp/pfl$(date +%s)" #Pod File List

## Indexing Script

find -type f | sed 's/^..//' | grep -i "\.opus\|\.m4a\|\.ogg\|\.webm\|\.mp3\|\.wav\|\.aif" > "$pfl"

# len=$(cat "$pfl" | wc -l)
len=$(wc -l < "$pfl")

echo """$len"" files to convert."

## Folder Script

if [ -d "$folder" ]; then
	echo """$folder"" directory exists. Continuing..."
elif [ "$len" = 0 ]; then
	echo "No music in this directory to convert."
else
	echo "Creating the directory ""$folder"" to store the ""$goal_ext""s."
	mkdir "$folder"
fi

## Conversion Script

for i in $(seq 1 "$len")
do
	file=$(awk NR=="$i" "$pfl")
	base="${file%.*}"
	ext="${file##*.}"
	#echo $file
	if [ "$ext" = "$goal_ext" ];
	then
		cp "$file" "$folder"
		echo "Successfully copied ""$file"" into ""$folder"""
	else
		echo "
		Converting ""$file"" into ""$base"$goal_ext
		ffmpeg -v quiet -hide_banner -i "$file" -ac 2 "$folder"/"$base""$goal_ext"
	fi
done

## Cleanup

rm "$pfl"
